const ADD_TODO = `ADD_TODO`;
const TOGGLE_TODO = `TOGGLE_TODO`;
const DELETE_TODO = `DELETE_TODO`;
const SET_FILTER = `SET_FILTER`;
const HIDE_NOTIFICATION = `HIDE_NOTIFICATION`;
const TODO_ADD_WITH_NOTIFICATION = `TODO_ADD_WITH_NOTIFICATION`;

export default {
  ADD_TODO,
  TOGGLE_TODO,
  DELETE_TODO,
  SET_FILTER,
  HIDE_NOTIFICATION,
  TODO_ADD_WITH_NOTIFICATION
};
